name: CI - Docker Compose Test Environment

on:
  push:
    branches:
      - main
      - dev
      - feature/**

env:
  COMPOSE_FILE: docker-compose.yaml
  COMPOSE_PROJECT_NAME: mlops_project

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🐳 Set up Docker
        run: |
          sudo apt update
          sudo apt install -y apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
          sudo apt update
          sudo apt install -y docker-ce

      - name: 📦 Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: 🚀 Start and build containers
        run: sudo docker-compose up -d --build

      - name: 🧪 Healthcheck: FastAPI
        run: curl --fail http://localhost:8000 || exit 1

      - name: 🧪 Healthcheck: Streamlit
        run: curl --fail http://localhost:8501 || exit 1

      - name: 🧪 Healthcheck: Airflow
        run: curl --fail http://localhost:8080 || echo "Airflow may not be ready yet"

      - name: 🧪 Healthcheck: MLflow
        run: curl --fail http://localhost:5002 || exit 1

      - name: 🧪 Healthcheck: MinIO
        run: curl --fail http://localhost:9000 || exit 1

      - name: 🧹 Stop and clean up
        if: always()
        run: sudo docker-compose down -v

