name: CI - Test API only

on:
  push:
    branches:
      - dev
      - main
      - feature/**

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Build and start API container
        run: docker-compose -f docker-compose.yaml up -d api

      - name: Wait and test FastAPI
        run: |
          for i in {1..10}; do
            echo "⏳ Waiting for API... attempt $i"
            curl --fail http://localhost:8000/docs && break
            sleep 3
          done

      - name: Clean up
        if: always()
        run: docker-compose -f docker-compose.yaml down -v

