name: CI - Test ML + MinIO + MLflow

on:
  push:
    branches:
      - dev
      - main
      - feature/**

jobs:
  test-ml-minio-mlflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Build ML, MinIO and MLflow containers
        run: docker-compose -f docker-compose.yaml build ml-train minio mlflow

      - name: Start MinIO and MLflow
        run: docker-compose -f docker-compose.yaml up -d minio mlflow

      - name: Wait for services to be ready
        run: |
          for i in {1..10}; do
            echo "⏳ Waiting for MinIO..."
            curl --fail http://localhost:9000 && break || sleep 3
          done
          for i in {1..10}; do
            echo "⏳ Waiting for MLflow..."
            curl --fail http://localhost:5002 && break || sleep 3
          done

      - name: Run ML training script
        run: docker-compose -f docker-compose.yaml run --rm ml-train python model_2.py

      - name: Clean up
        if: always()
        run: docker-compose -f docker-compose.yaml down -v
