name: CI - Test Full MLOps Stack

on:
  push:
    branches:
      - dev
      - main
      - feature/**

jobs:
  test-full-stack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Build all containers
        run: |
          docker-compose -f docker-compose.yaml build \
            postgres redis airflow airflow-scheduler \
            minio mlflow ml-train streamlit

      - name: Start backend services
        run: |
          docker-compose -f docker-compose.yaml up -d \
            postgres redis minio mlflow

      - name: Wait for MinIO and MLflow
        run: |
          for i in {1..10}; do
            echo "⏳ Waiting for MinIO..."
            curl --fail http://localhost:9000 && break || sleep 3
          done
          for i in {1..10}; do
            echo "⏳ Waiting for MLflow..."
            curl --fail http://localhost:5002 && break || sleep 3
          done

      - name: Run ML training script
        run: docker-compose -f docker-compose.yaml run --rm ml-train python model_2.py

      - name: Start Streamlit
        run: docker-compose -f docker-compose.yaml up -d streamlit

      - name: Wait and test Streamlit
        run: |
          for i in {1..10}; do
            echo "⌛ Waiting for Streamlit..."
            curl --fail http://localhost:8501 && break || sleep 3
          done

      - name: Start Airflow services
        run: docker-compose -f docker-compose.yaml up -d airflow airflow-scheduler

      - name: Wait for Airflow Webserver
        run: |
          for i in {1..10}; do
            echo "⌛ Waiting for Airflow..."
            curl --fail http://localhost:8080 && break || sleep 5
          done

      - name: List Airflow DAGs
        run: docker-compose -f docker-compose.yaml exec airflow airflow dags list

      - name: Clean up all containers
        if: always()
        run: docker-compose -f docker-compose.yaml down -v
